### ISSUE TITLE
Error when attempting to create RMap Agent or DiSCO, 

### ISSUE THREAD

**Issue by karenhanson** [rmap-project/rmap-docker#1]
Steps to replicate:
1) start up docker, per instructions in README.md, watch log until started.
2) log in to localhost:8080/app/admin/login using rmapAdmin/changeme (i.e. the defaults are not overridden). There will be a system error as it tries to create the admin account in the RMap triplestore.
3) In the log there is an exception similar to the one below (note this is from trying to POST a DiSCO using a new user, but the origin is the same)

```
22:52:07.960 [               qtp422250493-13] ERROR [       RMapApiExceptionHandler] - Error while attempting to retrieve the RMap Agent associated with the user; The RMap Agent information in the database is not well formed or has missing information; RepositoryException: Failed to get server protocol; no such resource on this server: http://rdf4j:8081/rdf4j-server/repositories/docker/size?context=%3Crmap%3Asrxegoj1v7%3E
info.rmapproject.api.exception.RMapApiException: The RMap Agent information in the database is not well formed or has missing information
        at info.rmapproject.api.exception.RMapApiException.wrap(RMapApiException.java:52)
        at info.rmapproject.api.auth.ApiUserServiceImpl.prepareUserForWriteAccess(ApiUserServiceImpl.java:165)
        at info.rmapproject.api.auth.ApiUserServiceImpl.prepareCurrentUserForWriteAccess(ApiUserServiceImpl.java:139)
        at info.rmapproject.api.responsemgr.DiscoResponseManager.createRMapDiSCO(DiscoResponseManager.java:439)
        at info.rmapproject.api.service.DiSCOApiService.apiCreateRMapDiSCO(DiSCOApiService.java:242)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:561)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
        at java.lang.Thread.run(Thread.java:748)
Caused by: info.rmapproject.auth.exception.RMapAuthException: The RMap Agent information in the database is not well formed or has missing information
        at info.rmapproject.auth.service.UserRMapAgentServiceImpl.createOrUpdateAgentFromUser(UserRMapAgentServiceImpl.java:133)
        at info.rmapproject.auth.service.RMapAuthServiceImpl.createOrUpdateAgentFromUser(RMapAuthServiceImpl.java:195)
        at info.rmapproject.api.auth.ApiUserServiceImpl.prepareUserForWriteAccess(ApiUserServiceImpl.java:162)
        ... 58 common frames omitted
Caused by: info.rmapproject.core.exception.RMapException: Exception thrown searching for object rmap:srxegoj1v7
        at info.rmapproject.core.rmapservice.impl.rdf4j.ORMapObjectMgr.isRMapType(ORMapObjectMgr.java:107)
        at info.rmapproject.core.rmapservice.impl.rdf4j.ORMapObjectMgr.isAgentId(ORMapObjectMgr.java:145)
        at info.rmapproject.core.rmapservice.impl.rdf4j.ORMapService.isAgentId(ORMapService.java:969)
        at info.rmapproject.auth.service.UserRMapAgentServiceImpl.createOrUpdateAgentFromUser(UserRMapAgentServiceImpl.java:111)
        ... 60 common frames omitted
Caused by: org.eclipse.rdf4j.repository.RepositoryException: Failed to get server protocol; no such resource on this server: http://rdf4j:8081/rdf4j-server/repositories/docker/size?context=%3Crmap%3Asrxegoj1v7%3E
        at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeOK(SPARQLProtocolSession.java:1080)
        at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.size(RDF4JProtocolSession.java:241)
        at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.size(HTTPRepositoryConnection.java:299)
        at info.rmapproject.core.rmapservice.impl.rdf4j.ORMapObjectMgr.isRMapType(ORMapObjectMgr.java:89)
        ... 63 common frames omitted
22:56:06.721 [               qtp422250493-13] INFO  [                   UserDaoImpl] - Api key list loaded successfully
```

**Comment by karenhanson** [comment]
Tested this in the latest version, it is now resolved.
